variational classifier is also called quantum parameterized circuits or quantum neural networks.
The algorithm contains few ingredients:
1. A circuit ansatz ( the architecture of the circuit)
2. cost function 
3. Training procedure ( gradient descent/ update circuit parameter) 




In [ ]:
!pip install pennylane

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import pandas as pd
import numpy as np
from pennylane import numpy as np
from sklearn.preprocessing import normalize
from sklearn.preprocessing import StandardScaler

import pennylane as qml
from pennylane.templates.embeddings import AngleEmbedding, AmplitudeEmbedding
from pennylane.optimize import AdamOptimizer
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler


import time
start = time.time()

In [ ]:
df = pd.read_csv('/content/ClaMP_Integrated-5184.csv', sep=',')

In [ ]:
df.drop(['packer_type'],axis=1,inplace=True)

In [ ]:
# Read out CSV and sets/samples creation

df = df.astype(float)
train,test = train_test_split(df, test_size=0.30, random_state=2)
train_set = train
test_set = test
train_set = train_set.sample(160)
test_set = test_set.sample(40)
np.random.seed(42)

In [ ]:
df.info

<bound method DataFrame.info of       e_cblp  e_cp  e_cparhdr  e_maxalloc   e_sp  e_lfanew  NumberOfSections  \
0      144.0   3.0        4.0     65535.0  184.0     256.0               4.0   
1      144.0   3.0        4.0     65535.0  184.0     184.0               4.0   
2      144.0   3.0        4.0     65535.0  184.0     272.0               5.0   
3      144.0   3.0        4.0     65535.0  184.0     184.0               1.0   
4      144.0   3.0        4.0     65535.0  184.0     224.0               5.0   
...      ...   ...        ...         ...    ...       ...               ...   
5205   144.0   3.0        4.0     65535.0  184.0     216.0               5.0   
5206    80.0   2.0        4.0     65535.0  184.0     256.0               7.0   
5207   144.0   3.0        4.0     65535.0  184.0     216.0               5.0   
5208   144.0   3.0        4.0     65535.0  184.0     248.0               5.0   
5209   144.0   3.0        4.0     65535.0  184.0     240.0               4.0   

      C

In [ ]:
df.describe()

e_cblp          e_cp     e_cparhdr    e_maxalloc          e_sp  \
count   5210.000000   5210.000000   5210.000000   5210.000000   5210.000000   
mean     152.658733     10.633589      8.903263  65137.618234    202.530902   
std      616.499070    392.745064    251.685103   5005.606042    968.625098   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%      144.000000      3.000000      4.000000  65535.000000    184.000000   
50%      144.000000      3.000000      4.000000  65535.000000    184.000000   
75%      144.000000      3.000000      4.000000  65535.000000    184.000000   
max    37008.000000  20050.000000  12851.000000  65535.000000  65534.000000   

          e_lfanew  NumberOfSections  CreationYear     FH_char0  FH_char1  \
count  5210.000000       5210.000000   5210.000000  5210.000000    5210.0   
mean    222.833013          4.662956      0.990403     0.362764       1.0   
std      48.591497          1.922882      0.097502     0.480844       0.0   
min      12.000000          1.000000      0.000000     0.000000       1.0   
25%     208.000000          4.000000      1.000000     0.000000       1.0   
50%     232.000000          5.000000      1.000000     0.000000       1.0   
75%     248.000000          5.000000      1.000000     1.000000       1.0   
max     648.000000         34.000000      1.000000     1.000000       1.0   

       ...  LoaderFlags  sus_sections  non_sus_sections       packer  \
count  ...  5210.000000   5210.000000       5210.000000  5210.000000   
mean   ...     0.999040      1.360845          3.302111     0.156430   
std    ...     0.030967      1.623972          1.146956     0.363297   
min    ...     0.000000      0.000000          0.000000     0.000000   
25%    ...     1.000000      1.000000          3.000000     0.000000   
50%    ...     1.000000      1.000000          4.000000     0.000000   
75%    ...     1.000000      2.000000          4.000000     0.000000   
max    ...     1.000000     31.000000          8.000000     1.000000   

            E_text       E_data      filesize       E_file     fileinfo  \
count  5210.000000  5210.000000  5.210000e+03  5210.000000  5210.000000   
mean      4.939586     2.523549  7.875718e+05     6.364756     0.544146   
std       2.521787     2.685909  5.293440e+06     1.119881     0.498095   
min       0.000000     0.000000  1.536000e+03     0.939626     0.000000   
25%       3.886006     0.000000  6.144000e+04     5.695785     0.000000   
50%       6.148211     1.555973  1.218560e+05     6.390618     1.000000   
75%       6.507072     4.685836  3.055480e+05     7.314531     1.000000   
max       7.999859     7.999620  1.657081e+08     7.999997     1.000000   

             class  
count  5210.000000  
mean      0.522457  
std       0.499543  
min       0.000000  
25%       0.000000  
50%       1.000000  
75%       1.000000  
max       1.000000  

[8 rows x 69 columns]

In [ ]:
# Separation of labels

x_train = train_set
y_train = train_set[['class']]

x_test = test_set
y_test = test_set[['class']]

In [ ]:
# Reduce dimensions using PCA to fit the dimensions with the qubits

n_dim = 2
pca = PCA(n_components=n_dim)
pca.fit(x_train)

x_train = pca.transform(x_train)

pca.fit(x_test)
x_test = pca.transform(x_test)

In [ ]:
# Normalize

std_scale = StandardScaler().fit(x_train)
data = std_scale.transform(x_train)

std_scale = StandardScaler().fit(x_test)
x_test = std_scale.transform(x_test)

In [ ]:
# Review the balance of the target variable in train

y_train.value_counts(normalize=True)*100

class
0.0      51.875
1.0      48.125
dtype: float64

In [ ]:
# Review the balance of the target variable in test

y_test.value_counts(normalize=True)*100

class
1.0      55.0
0.0      45.0
dtype: float64

In [ ]:
# Angle Encoding

num_qubits = n_dim

dev = qml.device('default.qubit', wires = num_qubits)

@qml.qnode(dev)
def circuit(parameters, data):
    for i in range(num_qubits):
        qml.Hadamard(wires = i)
    
    AngleEmbedding(features = data, wires = range(num_qubits), rotation = 'Y')
    
    qml.StronglyEntanglingLayers(weights = parameters, wires = range(num_qubits))
    
    return qml.expval(qml.PauliZ(0))

In [ ]:
num_layers = 5
weights_init = 0.01 * np.random.randn(num_layers, num_qubits, 3, requires_grad=True)
bias_init = np.array(0.0, requires_grad=True)

print(weights_init, bias_init)

[[[-0.00601707  0.01852278 -0.00013497]
  [-0.01057711  0.00822545 -0.01220844]]

 [[ 0.00208864 -0.0195967  -0.01328186]
  [ 0.00196861  0.00738467  0.00171368]]

 [[-0.00115648 -0.00301104 -0.01478522]
  [-0.00719844 -0.00460639  0.01057122]]

 [[ 0.00343618 -0.0176304   0.00324084]
  [-0.00385082 -0.00676922  0.00611676]]

 [[ 0.01031     0.0093128  -0.00839218]
  [-0.00309212  0.00331263  0.00975545]]] 0.0


In [ ]:
circuit(weights_init, data[0])

tensor(0.01214696, requires_grad=True)

In [ ]:
def variational_classifier(weights, bias, x):
    return circuit(weights, x) + bias


In [ ]:
def square_loss(labels, predictions):
    loss = 0
    for l, p in zip(labels, predictions):
        loss = loss + (l - p) ** 2

    loss = loss / len(labels)
    return loss


In [ ]:
def accuracy(labels, predictions):

    loss = 0
    for l, p in zip(labels, predictions):
        if abs(l - p) < 1e-5:
            loss = loss + 1
    loss = loss / len(labels)

    return loss

In [ ]:
def cost(weights, bias, X, Y):
    predictions = [variational_classifier(weights, bias, x) for x in X]
    return square_loss(Y, predictions)

In [ ]:
Y = np.array(y_train.values[:,0] * 2 - np.ones(len(y_train.values[:,0])), requires_grad = False)  # shift label from {0, 1} to {-1, 1}
X = np.array(data, requires_grad=False)

for i in range(5):
    print("X = {}, Y = {: d}".format(list(X[i]), int(Y[i])))

X = [tensor(-0.07954832, requires_grad=False), tensor(-0.25290842, requires_grad=False)], Y = -1
X = [tensor(-0.08034127, requires_grad=False), tensor(1.94352618, requires_grad=False)], Y =  1
X = [tensor(-0.08126536, requires_grad=False), tensor(4.36642967, requires_grad=False)], Y =  1
X = [tensor(-0.07521629, requires_grad=False), tensor(-0.52175067, requires_grad=False)], Y = -1
X = [tensor(-0.07755101, requires_grad=False), tensor(-0.25030712, requires_grad=False)], Y =  1


In [ ]:
opt = AdamOptimizer(stepsize=0.1, beta1=0.9, beta2=0.99, eps=1e-08)
batch_size = 10

In [ ]:
weights = weights_init
bias = bias_init

wbest = 0
bbest = 0
abest = 0

for it in range(100):

    # weights update by one optimizer step

    batch_index = np.random.randint(0, len(X), (batch_size,))
    X_batch = X[batch_index]
    Y_batch = Y[batch_index]
    weights, bias, _, _ = opt.step(cost, weights, bias, X_batch, Y_batch)

    # Compute the accuracy
    predictions = [np.sign(variational_classifier(weights, bias, x)) for x in X]
    
    if accuracy(Y, predictions) > abest:
        wbest = weights
        bbest = bias
        abest = accuracy(Y, predictions)
        print('New best')

    acc = accuracy(Y, predictions)

    print(
        "Iter: {:5d} | Cost: {:0.7f} | Accuracy: {:0.7f} ".format(
            it + 1, cost(weights, bias, X, Y), acc
        )
    )

New best
Iter:     1 | Cost: 1.0763623 | Accuracy: 0.5187500 
Iter:     2 | Cost: 1.0278761 | Accuracy: 0.4250000 
Iter:     3 | Cost: 1.1741594 | Accuracy: 0.4562500 
Iter:     4 | Cost: 1.1544134 | Accuracy: 0.4812500 
Iter:     5 | Cost: 1.0509583 | Accuracy: 0.4562500 
New best
Iter:     6 | Cost: 0.9984045 | Accuracy: 0.5375000 
New best
Iter:     7 | Cost: 1.0004401 | Accuracy: 0.5562500 
Iter:     8 | Cost: 1.0052084 | Accuracy: 0.5562500 
Iter:     9 | Cost: 1.0061520 | Accuracy: 0.5562500 
Iter:    10 | Cost: 1.0178625 | Accuracy: 0.3375000 
Iter:    11 | Cost: 1.0821308 | Accuracy: 0.4562500 
Iter:    12 | Cost: 1.1361917 | Accuracy: 0.4562500 
Iter:    13 | Cost: 1.1804824 | Accuracy: 0.4562500 
Iter:    14 | Cost: 1.0680494 | Accuracy: 0.4312500 
Iter:    15 | Cost: 1.0296217 | Accuracy: 0.5187500 
Iter:    16 | Cost: 1.0944602 | Accuracy: 0.5187500 
Iter:    17 | Cost: 1.1487291 | Accuracy: 0.5187500 
Iter:    18 | Cost: 1.1143382 | Accuracy: 0.5187500 
Iter:    19 | Cost:

In [ ]:
Yte = np.array(y_test.values[:,0] * 2 - np.ones(len(y_test.values[:,0])), requires_grad = False)
Xte = np.array(normalize(x_test), requires_grad=False)

In [ ]:
predictions = [np.sign(variational_classifier(wbest, bbest, x)) for x in Xte]
pred = [np.sign(variational_classifier(wbest, bbest, x)) for x in X]
acc = accuracy(Yte, predictions)

print(f'Cost: {cost(wbest, bbest, Xte, Yte)}, Accuracy: {np.round(acc, 2) * 100}%')

Cost: 0.9745669761192326, Accuracy: 60.0%


In [ ]:
pd.DataFrame((predictions, Yte), ('Predictions', 'Test')).T

Predictions  Test
0          1.0   1.0
1         -1.0  -1.0
2          1.0  -1.0
3         -1.0   1.0
4          1.0   1.0
5          1.0   1.0
6          1.0   1.0
7          1.0  -1.0
8          1.0   1.0
9         -1.0   1.0
10         1.0   1.0
11         1.0   1.0
12         1.0  -1.0
13         1.0   1.0
14         1.0   1.0
15         1.0  -1.0
16         1.0   1.0
17        -1.0  -1.0
18         1.0   1.0
19        -1.0  -1.0
20        -1.0   1.0
21         1.0  -1.0
22        -1.0  -1.0
23        -1.0   1.0
24         1.0   1.0
25         1.0   1.0
26         1.0   1.0
27         1.0  -1.0
28        -1.0  -1.0
29         1.0  -1.0
30         1.0   1.0
31         1.0   1.0
32        -1.0  -1.0
33         1.0  -1.0
34         1.0  -1.0
35         1.0  -1.0
36         1.0   1.0
37         1.0  -1.0
38         1.0  -1.0
39         1.0   1.0

In [ ]:
# Print the classification report and important metrics

print(metrics.classification_report(predictions,Yte))
print(metrics.precision_score(predictions,Yte))
print(metrics.recall_score(predictions,Yte))
print(metrics.f1_score(predictions,Yte))
print(metrics.balanced_accuracy_score(predictions,Yte))

              precision    recall  f1-score   support

        -1.0       0.33      0.60      0.43        10
         1.0       0.82      0.60      0.69        30

    accuracy                           0.60        40
   macro avg       0.58      0.60      0.56        40
weighted avg       0.70      0.60      0.63        40

0.8181818181818182
0.6
0.6923076923076923
0.6
